//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMP_TenantMaster
    {
        public CMP_TenantMaster()
        {
            this.CMP_IssueDetails = new HashSet<CMP_IssueDetails>();
        }
    
        public int Id { get; set; }
        public string TenantName { get; set; }
        public int ProjectId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<CMP_IssueDetails> CMP_IssueDetails { get; set; }
        public virtual CMP_ProjectMaster CMP_ProjectMaster { get; set; }
    }
}
