//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMP_IssueActivityDetails
    {
        public int Id { get; set; }
        public int ActivityTypeId { get; set; }
        public int IssueId { get; set; }
        public System.DateTime DateOfActivity { get; set; }
        public int UserId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual CMP_ActivityMaster CMP_ActivityMaster { get; set; }
        public virtual CMP_UserDetails CMP_UserDetails { get; set; }
    }
}
