//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMP_ProjectMaster
    {
        public CMP_ProjectMaster()
        {
            this.CMP_TenantMaster = new HashSet<CMP_TenantMaster>();
            this.CMP_UserDetails = new HashSet<CMP_UserDetails>();
            this.CMP_UserDetails1 = new HashSet<CMP_UserDetails>();
        }
    
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<CMP_TenantMaster> CMP_TenantMaster { get; set; }
        public virtual ICollection<CMP_UserDetails> CMP_UserDetails { get; set; }
        public virtual ICollection<CMP_UserDetails> CMP_UserDetails1 { get; set; }
    }
}
