//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMP_IssueDetails
    {
        public CMP_IssueDetails()
        {
            this.CMP_IssueAssignmentDetails = new HashSet<CMP_IssueAssignmentDetails>();
        }
    
        public int Id { get; set; }
        public string IssueType { get; set; }
        public string ExternalId { get; set; }
        public string Summary { get; set; }
        public int CategoryId { get; set; }
        public int StatusId { get; set; }
        public int TenantId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Priority { get; set; }
    
        public virtual CMP_CategoryMaster CMP_CategoryMaster { get; set; }
        public virtual ICollection<CMP_IssueAssignmentDetails> CMP_IssueAssignmentDetails { get; set; }
        public virtual CMP_TenantMaster CMP_TenantMaster { get; set; }
        public virtual CMP_IssueStatusMaster CMP_IssueStatusMaster { get; set; }
    }
}
