//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompassEntities : DbContext
    {
        public CompassEntities()
            : base("name=CompassEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMP_ActivityMaster> CMP_ActivityMaster { get; set; }
        public virtual DbSet<CMP_CategoryMaster> CMP_CategoryMaster { get; set; }
        public virtual DbSet<CMP_IssueActivityDetails> CMP_IssueActivityDetails { get; set; }
        public virtual DbSet<CMP_IssueAssignmentDetails> CMP_IssueAssignmentDetails { get; set; }
        public virtual DbSet<CMP_IssueDetails> CMP_IssueDetails { get; set; }
        public virtual DbSet<CMP_IssueStatusMaster> CMP_IssueStatusMaster { get; set; }
        public virtual DbSet<CMP_RoleMaster> CMP_RoleMaster { get; set; }
        public virtual DbSet<CMP_UserDetails> CMP_UserDetails { get; set; }
    }
}
